---
name: Build and Publish Docker Workflow
on:
  workflow_call:
    inputs:
      WORKDIR:
        required: false
        type: string
        default: ./
    secrets:
      IMAGE_TAG:
        required: true
      IMAGE_VERSION:
        required: true
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      GKE_SA_KEY:
        required: true
      PROJECT_ID:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: "270.0.0"
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Set up Docker credentials
      run: |-
        gcloud auth configure-docker -q

    - name: Build docker image
      working-directory: ${{ inputs.WORKDIR }}
      run: |-
        # pull latest image to use as cache
        docker pull ${{ secrets.IMAGE_TAG }}:latest || true

        docker build \
        --cache-from ${{ secrets.IMAGE_TAG }}:latest \
        -t ${{ secrets.IMAGE_TAG }}:latest \
        -t ${{ secrets.IMAGE_TAG }}:${{ secrets.IMAGE_VERSION }} \
        --build-arg NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }} \
        --build-arg NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }} \
        "."
      shell: bash

    - name: Push docker image
      run: |-
        docker push ${{ secrets.IMAGE_TAG }}:latest
        docker push ${{ secrets.IMAGE_TAG }}:${{ secrets.IMAGE_VERSION }}
      shell: bash



